version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: duckuser
      POSTGRES_PASSWORD: duckpass
      POSTGRES_DB: duckdb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  superset:
    image: apache/superset:3.1.0
    container_name: superset_app
    environment:
      - SUPERSET_SECRET_KEY=ducksecretkey
      - PYTHONPATH=/usr/local/lib/python3.10/site-packages
    ports:
      - "8088:8088"
    depends_on:
      - postgres
    volumes:
      - ./superset_home:/app/superset_home
